import streamlit as st
import pandas as pd
import numpy as np
import joblib
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, precision_score, \
    recall_score, f1_score, matthews_corrcoef

# Page Config
st.set_page_config(page_title="Classification Model Deployment", layout="wide")

st.title("🔬 ML Classification Dashboard")
st.markdown("Upload a CSV file to evaluate different classification models.")

# Sidebar
st.sidebar.header("Configuration")

# 1. Model Selection Dropdown
model_options = [
    "Logistic Regression",
    "Decision Tree",
    "KNN",
    "Naive Bayes",
    "Random Forest",
    "XGBoost"
]
selected_model_name = st.sidebar.selectbox("Select Model", model_options)


# Load the selected model and scaler
@st.cache_resource
def load_resources(model_name):
    # Map selection to filename
    file_map = {
        "Logistic Regression": "logistic_regression.pkl",
        "Decision Tree": "decision_tree.pkl",
        "KNN": "knn.pkl",
        "Naive Bayes": "naive_bayes.pkl",
        "Random Forest": "random_forest.pkl",
        "XGBoost": "xgboost.pkl"
    }
    try:
        model = joblib.load(f"model/{file_map[model_name]}")
        scaler = joblib.load("model/scaler.pkl")
        return model, scaler
    except FileNotFoundError:
        st.error(f"Model file for {model_name} not found. Did you run train_models.py?")
        return None, None


model, scaler = load_resources(selected_model_name)

# 2. Dataset Upload
uploaded_file = st.sidebar.file_uploader("Upload Test Data (CSV)", type=["csv"])

if uploaded_file is not None and model is not None:
    try:
        # Load Data
        df = pd.read_csv(uploaded_file)
        st.write(f"### Uploaded Data Preview ({df.shape[0]} rows)")
        st.dataframe(df.head())

        # Check for target column
        # Assuming the last column is target if 'target' isn't explicitly named,
        # or ask user to select. For this assignment, let's assume standard format.
        if 'target' in df.columns:
            target_col = 'target'
            X_test = df.drop(columns=[target_col])
            y_test = df[target_col]
        else:
            st.warning("Target column named 'target' not found. Using last column as target.")
            target_col = df.columns[-1]
            X_test = df.iloc[:, :-1]
            y_test = df.iloc[:, -1]

        # Preprocessing (Scaling if needed)
        if selected_model_name in ["Logistic Regression", "KNN"]:
            X_input = scaler.transform(X_test)
        else:
            X_input = X_test

        # Predictions
        if st.button("Run Prediction"):
            preds = model.predict(X_input)
            probs = model.predict_proba(X_input)[:, 1]

            # 3. Evaluation Metrics
            st.divider()
            st.subheader(f"Performance Metrics: {selected_model_name}")

            col1, col2, col3, col4, col5, col6 = st.columns(6)
            col1.metric("Accuracy", f"{accuracy_score(y_test, preds):.4f}")
            col2.metric("AUC Score", f"{roc_auc_score(y_test, probs):.4f}")
            col3.metric("Precision", f"{precision_score(y_test, preds):.4f}")
            col4.metric("Recall", f"{recall_score(y_test, preds):.4f}")
            col5.metric("F1 Score", f"{f1_score(y_test, preds):.4f}")
            col6.metric("MCC", f"{matthews_corrcoef(y_test, preds):.4f}")

            # 4. Confusion Matrix & Report
            st.divider()
            col_graph, col_text = st.columns([1, 1])

            with col_graph:
                st.subheader("Confusion Matrix")
                cm = confusion_matrix(y_test, preds)
                fig, ax = plt.subplots()
                sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)
                st.pyplot(fig)

            with col_text:
                st.subheader("Classification Report")
                report = classification_report(y_test, preds, output_dict=True)
                st.dataframe(pd.DataFrame(report).transpose())

    except Exception as e:
        st.error(f"Error processing the file: {e}")

elif uploaded_file is None:
    st.info(
        "Please upload a CSV file from the sidebar to start analysis. (Use the 'test_data.csv' generated by train_models.py)")